/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_boletaje;

import Bean.DistribucionBoletos;
import Dao.DistribucionDao;
import Dao.VehiculoDao;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ETS-SALVADOR
 */
public final class ImprimirBoletos extends javax.swing.JInternalFrame {

    DefaultTableModel tb;
    DistribucionDao DBD = new DistribucionDao();
    static public String Codigo;
    static public String Padron;
    VehiculoDao VD = new VehiculoDao();
    
    int contador = 0;
    
    
    
    Calendar fecha = new GregorianCalendar();        
            int ano = fecha.get(Calendar.YEAR);
            int mes = fecha.get(Calendar.MONTH)+1;
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
            
            
            
            String Fecha= String.valueOf(dia)+"/" +String.valueOf(mes+1)+ "/" +String.valueOf(ano);
            
            
            
    
    public ImprimirBoletos() {
        
        String Sdia,Saño,Smes;
        
        if(dia<10){
            Sdia="0"+dia;
        }else{
            Sdia=String.valueOf(dia);
        }
        
        if(mes<10){
            Smes="0"+mes;
        }else{
            Smes=String.valueOf(mes);
        }
        Saño=String.valueOf(ano);
        
        String Fecha= Sdia+"/" +Smes+ "/" +Saño.substring(2,4);
        
        initComponents();
        

        fechaRT.setText(VD.ObtenerfechaRT(Codigo));
        
        
        
        String [] data = DBD.Pegado(Codigo);
        
        if (Principal.usuario.equals("CALDERON")){
            lblusu.setText("CCC");
        }else if (Principal.usuario.equals("HAROLD")){
            lblusu.setText("H.P");
        }else if (Principal.usuario.equals("ESTEFANIE")){
            lblusu.setText("ES ☻");
        }        
        else{
            lblusu.setText(Principal.usuario.substring(0,2));
        }
        
        String Responsable=data[1];
        int hora, minutos;
        Calendar calendario = new GregorianCalendar();
        hora =calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        
        
        
        String Shora, Sminutos;
        if(hora < 10){
            Shora="0"+hora;
            
        }else{
            Shora= String.valueOf(hora);
        }
        
        
        if(minutos<10){
           Sminutos = "0"+ minutos; 
        }else{
            Sminutos = String.valueOf(minutos);
        }
        
        String horas = Shora + ":" + Sminutos;
        
        
        
            LlenarTabla(cuatro,"4.00",Codigo);
            LlenarTabla(tres50,"3.50",Codigo);
            LlenarTabla(tres,"3.00",Codigo);
            LlenarTabla(dos50,"2.50",Codigo);
            LlenarTabla(dos,"2.00",Codigo);
            LlenarTabla(uno50,"1.50",Codigo);
            LlenarTabla(cinco,"5.00",Codigo);
            LlenarTabla(uno,"1.00",Codigo);
            LlenarTabla(setenta,"0.70",Codigo);
            LlenarTabla(cincuenta,"0.50",Codigo);
            
            lblFecha.setText(Fecha);
            
            
            lblHora.setText(horas);
            lblPadron.setText(Padron);
            lblPadron2.setText(Padron);
            lblResponsable.setText(Responsable);
            lblContador.setText("NUMERO   DE   BOLETOS: "+contador);
            
            if(Fecha.equals(fechaRT.getText())){
                lblv.setForeground(new java.awt.Color(255, 0, 0));
                fechaRT.setForeground(new java.awt.Color(255, 0, 0));
            }
            
            Imprimir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlboleto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb35 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb4 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb25 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb12 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb15 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tb50 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tb70 = new javax.swing.JTable();
        controlboleto1 = new javax.swing.JPanel();
        f1 = new javax.swing.JPanel();
        f4 = new javax.swing.JPanel();
        f3 = new javax.swing.JPanel();
        f5 = new javax.swing.JPanel();
        f6 = new javax.swing.JPanel();
        f7 = new javax.swing.JPanel();
        f8 = new javax.swing.JPanel();
        f9 = new javax.swing.JPanel();
        f10 = new javax.swing.JPanel();
        f11 = new javax.swing.JPanel();
        f12 = new javax.swing.JPanel();
        f13 = new javax.swing.JPanel();
        f14 = new javax.swing.JPanel();
        f15 = new javax.swing.JPanel();
        f16 = new javax.swing.JPanel();
        f17 = new javax.swing.JPanel();
        f18 = new javax.swing.JPanel();
        f19 = new javax.swing.JPanel();
        f20 = new javax.swing.JPanel();
        f21 = new javax.swing.JPanel();
        f22 = new javax.swing.JPanel();
        f23 = new javax.swing.JPanel();
        f24 = new javax.swing.JPanel();
        f25 = new javax.swing.JPanel();
        f26 = new javax.swing.JPanel();
        f27 = new javax.swing.JPanel();
        f28 = new javax.swing.JPanel();
        f29 = new javax.swing.JPanel();
        f30 = new javax.swing.JPanel();
        f36 = new javax.swing.JPanel();
        f40 = new javax.swing.JPanel();
        f39 = new javax.swing.JPanel();
        f41 = new javax.swing.JPanel();
        f35 = new javax.swing.JPanel();
        f37 = new javax.swing.JPanel();
        f38 = new javax.swing.JPanel();
        f43 = new javax.swing.JPanel();
        f34 = new javax.swing.JPanel();
        f42 = new javax.swing.JPanel();
        f31 = new javax.swing.JPanel();
        lblPadron2 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tres50 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        cuatro = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        tres = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        dos50 = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        cinco = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        uno = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        uno50 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        dos = new javax.swing.JTable();
        jScrollPane19 = new javax.swing.JScrollPane();
        cincuenta = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        setenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblPadron = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblResponsable = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        fechaRT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblusu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblv = new javax.swing.JLabel();
        f2 = new javax.swing.JPanel();
        f32 = new javax.swing.JPanel();
        f33 = new javax.swing.JPanel();

        controlboleto.setBorder(javax.swing.BorderFactory.createTitledBorder("BOLETOS DISPONIBLES"));

        tb35.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "3.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb35MousePressed(evt);
            }
        });
        tb35.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb35KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb35);

        tb4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "4.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb4MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb4);

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "3.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb3MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tb3);

        tb25.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "2.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb25MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tb25);

        tb12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.20"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb12MousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tb12);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb1MousePressed(evt);
            }
        });
        tb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb1KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(tb1);

        tb15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb15MousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(tb15);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "2.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb2MousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(tb2);

        tb50.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "0.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb50MousePressed(evt);
            }
        });
        jScrollPane9.setViewportView(tb50);

        tb70.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "0.70"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb70MousePressed(evt);
            }
        });
        jScrollPane10.setViewportView(tb70);

        javax.swing.GroupLayout controlboletoLayout = new javax.swing.GroupLayout(controlboleto);
        controlboleto.setLayout(controlboletoLayout);
        controlboletoLayout.setHorizontalGroup(
            controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlboletoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        controlboletoLayout.setVerticalGroup(
            controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlboletoLayout.createSequentialGroup()
                .addGroup(controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(controlboletoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlboletoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(966, 527));
        setMinimumSize(new java.awt.Dimension(966, 527));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlboleto1.setBackground(new java.awt.Color(255, 255, 255));
        controlboleto1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOLETOS     DISPONIBLES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        controlboleto1.setForeground(new java.awt.Color(102, 102, 102));
        controlboleto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f1.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f1Layout = new javax.swing.GroupLayout(f1);
        f1.setLayout(f1Layout);
        f1Layout.setHorizontalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f1Layout.setVerticalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 40));

        f4.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f4Layout = new javax.swing.GroupLayout(f4);
        f4.setLayout(f4Layout);
        f4Layout.setHorizontalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f4Layout.setVerticalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 80, 40));

        f3.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f3Layout = new javax.swing.GroupLayout(f3);
        f3.setLayout(f3Layout);
        f3Layout.setHorizontalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f3Layout.setVerticalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 40));

        f5.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f5Layout = new javax.swing.GroupLayout(f5);
        f5.setLayout(f5Layout);
        f5Layout.setHorizontalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f5Layout.setVerticalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 80, 40));

        f6.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f6Layout = new javax.swing.GroupLayout(f6);
        f6.setLayout(f6Layout);
        f6Layout.setHorizontalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f6Layout.setVerticalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 80, 40));

        f7.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f7Layout = new javax.swing.GroupLayout(f7);
        f7.setLayout(f7Layout);
        f7Layout.setHorizontalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f7Layout.setVerticalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 80, 40));

        f8.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f8Layout = new javax.swing.GroupLayout(f8);
        f8.setLayout(f8Layout);
        f8Layout.setHorizontalGroup(
            f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f8Layout.setVerticalGroup(
            f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 80, 40));

        f9.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f9Layout = new javax.swing.GroupLayout(f9);
        f9.setLayout(f9Layout);
        f9Layout.setHorizontalGroup(
            f9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f9Layout.setVerticalGroup(
            f9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 80, 40));

        f10.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f10Layout = new javax.swing.GroupLayout(f10);
        f10.setLayout(f10Layout);
        f10Layout.setHorizontalGroup(
            f10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f10Layout.setVerticalGroup(
            f10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 80, 40));

        f11.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f11Layout = new javax.swing.GroupLayout(f11);
        f11.setLayout(f11Layout);
        f11Layout.setHorizontalGroup(
            f11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f11Layout.setVerticalGroup(
            f11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 80, 40));

        f12.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f12Layout = new javax.swing.GroupLayout(f12);
        f12.setLayout(f12Layout);
        f12Layout.setHorizontalGroup(
            f12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f12Layout.setVerticalGroup(
            f12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 40));

        f13.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f13Layout = new javax.swing.GroupLayout(f13);
        f13.setLayout(f13Layout);
        f13Layout.setHorizontalGroup(
            f13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f13Layout.setVerticalGroup(
            f13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 40));

        f14.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f14Layout = new javax.swing.GroupLayout(f14);
        f14.setLayout(f14Layout);
        f14Layout.setHorizontalGroup(
            f14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f14Layout.setVerticalGroup(
            f14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, 40));

        f15.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f15Layout = new javax.swing.GroupLayout(f15);
        f15.setLayout(f15Layout);
        f15Layout.setHorizontalGroup(
            f15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f15Layout.setVerticalGroup(
            f15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 80, 40));

        f16.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f16Layout = new javax.swing.GroupLayout(f16);
        f16.setLayout(f16Layout);
        f16Layout.setHorizontalGroup(
            f16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f16Layout.setVerticalGroup(
            f16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 80, 40));

        f17.setBackground(new Color(122,181,255,50));

        javax.swing.GroupLayout f17Layout = new javax.swing.GroupLayout(f17);
        f17.setLayout(f17Layout);
        f17Layout.setHorizontalGroup(
            f17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f17Layout.setVerticalGroup(
            f17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 80, 40));

        f18.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f18Layout = new javax.swing.GroupLayout(f18);
        f18.setLayout(f18Layout);
        f18Layout.setHorizontalGroup(
            f18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f18Layout.setVerticalGroup(
            f18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 80, 40));

        f19.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f19Layout = new javax.swing.GroupLayout(f19);
        f19.setLayout(f19Layout);
        f19Layout.setHorizontalGroup(
            f19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f19Layout.setVerticalGroup(
            f19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 80, 40));

        f20.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f20Layout = new javax.swing.GroupLayout(f20);
        f20.setLayout(f20Layout);
        f20Layout.setHorizontalGroup(
            f20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f20Layout.setVerticalGroup(
            f20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 80, 40));

        f21.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f21Layout = new javax.swing.GroupLayout(f21);
        f21.setLayout(f21Layout);
        f21Layout.setHorizontalGroup(
            f21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f21Layout.setVerticalGroup(
            f21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 80, 40));

        f22.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f22Layout = new javax.swing.GroupLayout(f22);
        f22.setLayout(f22Layout);
        f22Layout.setHorizontalGroup(
            f22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f22Layout.setVerticalGroup(
            f22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 40));

        f23.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f23Layout = new javax.swing.GroupLayout(f23);
        f23.setLayout(f23Layout);
        f23Layout.setHorizontalGroup(
            f23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f23Layout.setVerticalGroup(
            f23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 80, 40));

        f24.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f24Layout = new javax.swing.GroupLayout(f24);
        f24.setLayout(f24Layout);
        f24Layout.setHorizontalGroup(
            f24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f24Layout.setVerticalGroup(
            f24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 80, 40));

        f25.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f25Layout = new javax.swing.GroupLayout(f25);
        f25.setLayout(f25Layout);
        f25Layout.setHorizontalGroup(
            f25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f25Layout.setVerticalGroup(
            f25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 80, 40));

        f26.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f26Layout = new javax.swing.GroupLayout(f26);
        f26.setLayout(f26Layout);
        f26Layout.setHorizontalGroup(
            f26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f26Layout.setVerticalGroup(
            f26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 80, 40));

        f27.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f27Layout = new javax.swing.GroupLayout(f27);
        f27.setLayout(f27Layout);
        f27Layout.setHorizontalGroup(
            f27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f27Layout.setVerticalGroup(
            f27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 80, 40));

        f28.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f28Layout = new javax.swing.GroupLayout(f28);
        f28.setLayout(f28Layout);
        f28Layout.setHorizontalGroup(
            f28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f28Layout.setVerticalGroup(
            f28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 80, 40));

        f29.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f29Layout = new javax.swing.GroupLayout(f29);
        f29.setLayout(f29Layout);
        f29Layout.setHorizontalGroup(
            f29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f29Layout.setVerticalGroup(
            f29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f29, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 80, 40));

        f30.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f30Layout = new javax.swing.GroupLayout(f30);
        f30.setLayout(f30Layout);
        f30Layout.setHorizontalGroup(
            f30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f30Layout.setVerticalGroup(
            f30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f30, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 80, 40));

        f36.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f36Layout = new javax.swing.GroupLayout(f36);
        f36.setLayout(f36Layout);
        f36Layout.setHorizontalGroup(
            f36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f36Layout.setVerticalGroup(
            f36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f36, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 80, 40));

        f40.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f40Layout = new javax.swing.GroupLayout(f40);
        f40.setLayout(f40Layout);
        f40Layout.setHorizontalGroup(
            f40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f40Layout.setVerticalGroup(
            f40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f40, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 80, 40));

        f39.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f39Layout = new javax.swing.GroupLayout(f39);
        f39.setLayout(f39Layout);
        f39Layout.setHorizontalGroup(
            f39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f39Layout.setVerticalGroup(
            f39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f39, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 80, 40));

        f41.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f41Layout = new javax.swing.GroupLayout(f41);
        f41.setLayout(f41Layout);
        f41Layout.setHorizontalGroup(
            f41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f41Layout.setVerticalGroup(
            f41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 80, 40));

        f35.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f35Layout = new javax.swing.GroupLayout(f35);
        f35.setLayout(f35Layout);
        f35Layout.setHorizontalGroup(
            f35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f35Layout.setVerticalGroup(
            f35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f35, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 80, 40));

        f37.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f37Layout = new javax.swing.GroupLayout(f37);
        f37.setLayout(f37Layout);
        f37Layout.setHorizontalGroup(
            f37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f37Layout.setVerticalGroup(
            f37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f37, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 80, 40));

        f38.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f38Layout = new javax.swing.GroupLayout(f38);
        f38.setLayout(f38Layout);
        f38Layout.setHorizontalGroup(
            f38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f38Layout.setVerticalGroup(
            f38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 80, 40));

        f43.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f43Layout = new javax.swing.GroupLayout(f43);
        f43.setLayout(f43Layout);
        f43Layout.setHorizontalGroup(
            f43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f43Layout.setVerticalGroup(
            f43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 40));

        f34.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f34Layout = new javax.swing.GroupLayout(f34);
        f34.setLayout(f34Layout);
        f34Layout.setHorizontalGroup(
            f34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f34Layout.setVerticalGroup(
            f34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f34, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 80, 40));

        f42.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f42Layout = new javax.swing.GroupLayout(f42);
        f42.setLayout(f42Layout);
        f42Layout.setHorizontalGroup(
            f42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f42Layout.setVerticalGroup(
            f42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 80, 40));

        f31.setBackground(new Color(122,181,255,80));

        javax.swing.GroupLayout f31Layout = new javax.swing.GroupLayout(f31);
        f31.setLayout(f31Layout);
        f31Layout.setHorizontalGroup(
            f31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f31Layout.setVerticalGroup(
            f31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 80, 40));

        lblPadron2.setFont(new java.awt.Font("Tahoma", 1, 165)); // NOI18N
        lblPadron2.setForeground(new java.awt.Color(102, 102, 102));
        lblPadron2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPadron2.setText("jLabel2");
        controlboleto1.add(lblPadron2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 890, -1));

        tres50.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tres50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tres50.setForeground(new java.awt.Color(102, 102, 102));
        tres50.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "3.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tres50);

        controlboleto1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 82, 280));

        cuatro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cuatro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cuatro.setForeground(new java.awt.Color(102, 102, 102));
        cuatro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "4.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane12.setViewportView(cuatro);

        controlboleto1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 82, 280));

        tres.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tres.setForeground(new java.awt.Color(102, 102, 102));
        tres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "3.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(tres);

        controlboleto1.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 82, 280));

        dos50.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dos50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dos50.setForeground(new java.awt.Color(102, 102, 102));
        dos50.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "2.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane14.setViewportView(dos50);

        controlboleto1.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 82, 280));

        cinco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cinco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cinco.setForeground(new java.awt.Color(102, 102, 102));
        cinco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "5.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane15.setViewportView(cinco);

        controlboleto1.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 82, 280));

        uno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        uno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uno.setForeground(new java.awt.Color(102, 102, 102));
        uno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane16.setViewportView(uno);

        controlboleto1.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 82, 280));

        uno50.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        uno50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uno50.setForeground(new java.awt.Color(102, 102, 102));
        uno50.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane17.setViewportView(uno50);

        controlboleto1.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 82, 280));

        dos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dos.setForeground(new java.awt.Color(102, 102, 102));
        dos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "2.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane18.setViewportView(dos);

        controlboleto1.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 82, 280));

        cincuenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cincuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cincuenta.setForeground(new java.awt.Color(102, 102, 102));
        cincuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "0.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cincuenta.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane19.setViewportView(cincuenta);

        controlboleto1.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 82, 280));

        setenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setenta.setForeground(new java.awt.Color(102, 102, 102));
        setenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "0.70"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane20.setViewportView(setenta);

        controlboleto1.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 82, 280));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("PADRON");
        controlboleto1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));

        lblPadron.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblPadron.setForeground(new java.awt.Color(102, 102, 102));
        lblPadron.setText("999");
        controlboleto1.add(lblPadron, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("RESPONSABLE:");
        controlboleto1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 28, 108, -1));

        lblResponsable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResponsable.setForeground(new java.awt.Color(102, 102, 102));
        lblResponsable.setText("jLabel3");
        controlboleto1.add(lblResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 27, 564, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(102, 102, 102));
        lblFecha.setText("jLabel4");
        controlboleto1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 82, -1));

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHora.setForeground(new java.awt.Color(102, 102, 102));
        lblHora.setText("jLabel4");
        controlboleto1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 106, -1));

        lblContador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblContador.setForeground(new java.awt.Color(102, 102, 102));
        lblContador.setText("jLabel3");
        controlboleto1.add(lblContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 258, -1));

        fechaRT.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        fechaRT.setForeground(new java.awt.Color(102, 102, 102));
        fechaRT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaRT.setText("01/01/01");
        controlboleto1.add(fechaRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOTA:  EL  OPERADOR  SE  HARÁ  RESPONSABLE  POR  LA  PERDIDA  O  MAL  USO  DE  LOS  BOLETOS");
        controlboleto1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 881, -1));

        lblusu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusu.setForeground(new java.awt.Color(102, 102, 102));
        lblusu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusu.setText("jLabel5");
        controlboleto1.add(lblusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LA  PERDIDA  DE  ESTA  HOJA DE  LIQUIDACIÓN  AMERITA  UNA  MULTA  DE  S/10.00");
        controlboleto1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 881, -1));

        lblv.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblv.setForeground(new java.awt.Color(102, 102, 102));
        lblv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblv.setText("VENCIMIENTO DE REVISION TECNICA:");
        controlboleto1.add(lblv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 350, -1));

        f2.setBackground(new Color(0,153,255,150));

        javax.swing.GroupLayout f2Layout = new javax.swing.GroupLayout(f2);
        f2.setLayout(f2Layout);
        f2Layout.setHorizontalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f2Layout.setVerticalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 40));

        f32.setBackground(new Color(0,153,255,150));

        javax.swing.GroupLayout f32Layout = new javax.swing.GroupLayout(f32);
        f32.setLayout(f32Layout);
        f32Layout.setHorizontalGroup(
            f32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f32Layout.setVerticalGroup(
            f32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, 40));

        f33.setBackground(new Color(0,153,255,150));

        javax.swing.GroupLayout f33Layout = new javax.swing.GroupLayout(f33);
        f33.setLayout(f33Layout);
        f33Layout.setHorizontalGroup(
            f33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        f33Layout.setVerticalGroup(
            f33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        controlboleto1.add(f33, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 80, 40));

        getContentPane().add(controlboleto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 920, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void LlenarTabla(javax.swing.JTable tabla, String precio, String padron){
        
        ArrayList<DistribucionBoletos> ListaBoletos;
        ListaBoletos = DBD.ObtenerBoletos(precio, padron);
        tb =(DefaultTableModel)tabla.getModel();
        ListaBoletos.forEach((obj) -> {
            tb.addRow(new Object[] {obj.getInicio()});
            contador++;
        });
    }
    
     public void Imprimir(){
        
        printRecord(controlboleto1);
        
        
        
        
}
    
    
     public void printRecord(JPanel panel){
        // Create PrinterJob Here
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("CONTROL BOLETOS - GAAA");
        // Set Printable
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                // Check If No Printable Content
                if(pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }                
                // Make 2D Graphics to map content
                Graphics2D graphics2D = (Graphics2D)graphics;
                // Set Graphics Translations
                // A Little Correction here Multiplication was not working so I replaced with addition
                graphics2D.translate(pageFormat.getImageableX()+10, pageFormat.getImageableY()+10);
                // This is a page scale. Default should be 0.3 I am using 0.5
                graphics2D.scale(0.6, 0.8);                
                // Now paint panel as graphics2D
                panel.paint(graphics2D);                
                // return if page exists
                return Printable.PAGE_EXISTS;            }
        });
        // Store printerDialog as boolean
        boolean returningResult = printerJob.printDialog();
        // check if dilog is showing
        if(returningResult){
            // Use try catch exeption for failure
            try{
                // Now call print method inside printerJob to print
                printerJob.print();
               
            }catch (PrinterException printerException){
                
            }
        }
    }
    private void tb35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb35MousePressed
        
    }//GEN-LAST:event_tb35MousePressed

    private void tb35KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb35KeyPressed

    }//GEN-LAST:event_tb35KeyPressed

    private void tb4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb4MousePressed
        
    }//GEN-LAST:event_tb4MousePressed

    private void tb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb3MousePressed
        
    }//GEN-LAST:event_tb3MousePressed

    private void tb25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb25MousePressed
        
    }//GEN-LAST:event_tb25MousePressed

    private void tb12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb12MousePressed

    }//GEN-LAST:event_tb12MousePressed

    private void tb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MousePressed
       
    }//GEN-LAST:event_tb1MousePressed

    private void tb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb1KeyPressed

    }//GEN-LAST:event_tb1KeyPressed

    private void tb15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb15MousePressed
       
    }//GEN-LAST:event_tb15MousePressed

    private void tb2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MousePressed
        
    }//GEN-LAST:event_tb2MousePressed

    private void tb50MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb50MousePressed
    
    }//GEN-LAST:event_tb50MousePressed

    private void tb70MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb70MousePressed

    }//GEN-LAST:event_tb70MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable cinco;
    public static javax.swing.JTable cincuenta;
    private javax.swing.JPanel controlboleto;
    public static javax.swing.JPanel controlboleto1;
    public static javax.swing.JTable cuatro;
    public static javax.swing.JTable dos;
    public static javax.swing.JTable dos50;
    private javax.swing.JPanel f1;
    private javax.swing.JPanel f10;
    private javax.swing.JPanel f11;
    private javax.swing.JPanel f12;
    private javax.swing.JPanel f13;
    private javax.swing.JPanel f14;
    private javax.swing.JPanel f15;
    private javax.swing.JPanel f16;
    private javax.swing.JPanel f17;
    private javax.swing.JPanel f18;
    private javax.swing.JPanel f19;
    private javax.swing.JPanel f2;
    private javax.swing.JPanel f20;
    private javax.swing.JPanel f21;
    private javax.swing.JPanel f22;
    private javax.swing.JPanel f23;
    private javax.swing.JPanel f24;
    private javax.swing.JPanel f25;
    private javax.swing.JPanel f26;
    private javax.swing.JPanel f27;
    private javax.swing.JPanel f28;
    private javax.swing.JPanel f29;
    private javax.swing.JPanel f3;
    private javax.swing.JPanel f30;
    private javax.swing.JPanel f31;
    private javax.swing.JPanel f32;
    private javax.swing.JPanel f33;
    private javax.swing.JPanel f34;
    private javax.swing.JPanel f35;
    private javax.swing.JPanel f36;
    private javax.swing.JPanel f37;
    private javax.swing.JPanel f38;
    private javax.swing.JPanel f39;
    private javax.swing.JPanel f4;
    private javax.swing.JPanel f40;
    private javax.swing.JPanel f41;
    private javax.swing.JPanel f42;
    private javax.swing.JPanel f43;
    private javax.swing.JPanel f5;
    private javax.swing.JPanel f6;
    private javax.swing.JPanel f7;
    private javax.swing.JPanel f8;
    private javax.swing.JPanel f9;
    public static javax.swing.JLabel fechaRT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblPadron;
    private javax.swing.JLabel lblPadron2;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblusu;
    private javax.swing.JLabel lblv;
    public static javax.swing.JTable setenta;
    public static javax.swing.JTable tb1;
    public static javax.swing.JTable tb12;
    public static javax.swing.JTable tb15;
    public static javax.swing.JTable tb2;
    public static javax.swing.JTable tb25;
    public static javax.swing.JTable tb3;
    public static javax.swing.JTable tb35;
    public static javax.swing.JTable tb4;
    public static javax.swing.JTable tb50;
    public static javax.swing.JTable tb70;
    public static javax.swing.JTable tres;
    public static javax.swing.JTable tres50;
    public static javax.swing.JTable uno;
    public static javax.swing.JTable uno50;
    // End of variables declaration//GEN-END:variables
}
