/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_boletaje;

import Bean.Personal;
import Dao.PersonalDao;
import Util.ConexionBD;
import java.net.URL;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Harold7v7
 */
public class REPORTEXSOCIO extends javax.swing.JInternalFrame {

    /**
     * Creates new form REPORTEXSOCIO
     */
    DefaultTableModel tb;
    
    public REPORTEXSOCIO() {
        Calendar fecha = new GregorianCalendar();        
            int ano = fecha.get(Calendar.YEAR);
            int mes = fecha.get(Calendar.MONTH);
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
            String Fecha= String.valueOf(dia)+"/" +String.valueOf(mes+1)+ "/" +String.valueOf(ano);
            
        initComponents();
        
        LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calendario = new rojerusan.RSCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpropietario = new javax.swing.JTable();
        rSButton1 = new rojeru_san.RSButton();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();

        setClosable(true);
        setTitle("PRODUCCION X SOCIO");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calendario.setFormatoFecha("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tpropietario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "APELIIDO PATERNO", "NOMBRES Y APELLIDOS"
            }
        ));
        jScrollPane1.setViewportView(tpropietario);

        rSButton1.setText("MENSUAL");
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });

        rSButton2.setText("DIARIO");
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });

        rSButton3.setText("SEMANAL");
        rSButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
        int fila = tpropietario.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"SELECCIONE UN PROPIETARIO","ERROR",0);
        }else{
            try {
                
                int mes = calendario.currentMonth+1;
                int year = calendario.currentYear;
                
                ConexionBD con = new ConexionBD();
                Connection conn = con.getConexion();
                JasperReport reporte = null;
                //String path ="src\\reportes\\report1.jasper";
                Map parametro = new HashMap();
                parametro.put("mes",mes );
                parametro.put("year", year);
                parametro.put("Propietario", tpropietario.getValueAt(fila, 0).toString());
                parametro.put("nombre",tpropietario.getValueAt(fila,1).toString()+" "+tpropietario.getValueAt(fila,2).toString()+" "+tpropietario.getValueAt(fila,3).toString());
                URL path = this.getClass().getResource("/reportes/REPORTEMENSUALBOLETOxSocio.jasper");
                reporte = (JasperReport) JRLoader.loadObject(path);                
                JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro,conn);
                JasperViewer view = new JasperViewer(jprint,false); 
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
                
            } catch (JRException ex) {
                Logger.getLogger(ReportedeProduccion.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        }
        
        
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        int fila = tpropietario.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"SELECCIONE UN PROPIETARIO","ERROR",0);
        }else{
            try {
                
                
                
                ConexionBD con = new ConexionBD();
                Connection conn = con.getConexion();
                JasperReport reporte = null;
                //String path ="src\\reportes\\report1.jasper";
                Map parametro = new HashMap();
                System.err.println(calendario.getFechaSeleccionada());
                parametro.put("fecha",calendario.getFechaSeleccionada());                
                parametro.put("propietario", tpropietario.getValueAt(fila, 0).toString());
                parametro.put("Npropietario",tpropietario.getValueAt(fila,1).toString()+" "+tpropietario.getValueAt(fila,2).toString()+" "+tpropietario.getValueAt(fila,3).toString());
                URL path = this.getClass().getResource("/reportes/REPORTEBOLETAJEXSOCIO.jasper");
                reporte = (JasperReport) JRLoader.loadObject(path);                
                JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro,conn);
                JasperViewer view = new JasperViewer(jprint,false); 
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
                
            } catch (JRException ex) {
                Logger.getLogger(ReportedeProduccion.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        }
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton3ActionPerformed
        int fila = tpropietario.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"SELECCIONE UN PROPIETARIO","ERROR",0);
        }else{
            try {               
                ConexionBD con = new ConexionBD();
                Connection conn = con.getConexion();
                JasperReport reporte = null;
                //String path ="src\\reportes\\report1.jasper";
                Map parametro = new HashMap();
                System.err.println(calendario.getFechaSeleccionada());
                parametro.put("fecha",calendario.getFechaSeleccionada());                
                parametro.put("Propietario", tpropietario.getValueAt(fila, 0).toString());
                parametro.put("nombre",tpropietario.getValueAt(fila,1).toString()+" "+tpropietario.getValueAt(fila,2).toString()+" "+tpropietario.getValueAt(fila,3).toString());
                URL path = this.getClass().getResource("/reportes/REPORTESEMANALBOLETOxSocio.jasper");
                reporte = (JasperReport) JRLoader.loadObject(path);                
                JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro,conn);
                JasperViewer view = new JasperViewer(jprint,false); 
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
                
            } catch (JRException ex) {
                Logger.getLogger(ReportedeProduccion.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        }
    }//GEN-LAST:event_rSButton3ActionPerformed
    public void LlenarTabla(){
        PersonalDao PD = new PersonalDao();
        
        ArrayList<Personal> ListarPropietario;
        ListarPropietario = PD.ObtenerPropietario1();
        tb =(DefaultTableModel)tpropietario.getModel();
        ListarPropietario.forEach((obj) -> {
            tb.addRow(new Object[] {obj.getTidentificacion(),obj.getNombre(),obj.getApellidopa(),obj.getApellidoma()});
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSCalendar calendario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private javax.swing.JTable tpropietario;
    // End of variables declaration//GEN-END:variables
}
